Fix SPickleTools.dumps_with_external_ids() By accident commit 49a6219a853 also changed a single logger call in SPickleTools.dumps_with_external_ids(). This caused AttributeErrors: ... object has no attribute '_logger'. This commit restores the original code.